version: 0.1.0-{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.6"
stack: python %PYTHON%
install:
- cmd: pip install conan
- cmd: git submodule update --init --recursive
- sh: pip install conan
- sh: git submodule update --init --recursive
build_script:  
- cmd: .\build.cmd
- sh: sh build.sh
artifacts:
- path: out/bin
  name: ncc